Repository Azure-Samples/kaito-sample-repo, pull requests merged in 2025-05, with the labels that each got.

#3 init project
  .devcontainer/devcontainer.json
  .devcontainer/post-install.sh
  .dockerignore
  .github/workflows/lint.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
  .gitignore
  .golangci.yml
  Dockerfile
  Makefile
  PROJECT
  README.md
  api/v1alpha1/batchjob_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/kaito.dev_batchjobs.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/default/cert_metrics_manager_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/network-policy/allow-metrics-traffic.yaml
  config/network-policy/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/prometheus/monitor_tls_patch.yaml
  config/rbac/batchjob_admin_role.yaml
  config/rbac/batchjob_editor_role.yaml
  config/rbac/batchjob_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/kustomization.yaml
  config/samples/v1alpha1_batchjob.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  internal/controller/batchjob_controller.go
  internal/controller/batchjob_controller_test.go
  internal/controller/suite_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/utils/utils.go
Labels: Review effort 3/5

#10 Update README.md with context and contributing guidelines
  README.md
Labels: Review effort 2/5

#11 add demo
  demo/pr-agent/configuration.yaml
  demo/pr-agent/deployment.yaml
  demo/pr-agent/gateway/gateway.yaml
  demo/pr-agent/gateway/httproute.yaml
  demo/workspace/inference/inference-with-adapter.yaml
  demo/workspace/inference/inference.yaml
  demo/workspace/tuning/go-operator-reviewer-data.parquet
  demo/workspace/tuning/tuning.yaml
Labels: Review effort 4/5
